PYTHON ?= python3

test:
	$(PYTHON) test/logictest.py

console:
	$(PYTHON) app/console/__main__.py

clean:
	rm -rf stetris/__pycache__ test/__pycache__ app/console/__pycache__ __pycache__

.PHONY: test console clean
